name: Build JAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Clean and Build JAR
      run: ./gradlew clean jar
      
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.ref_name }}
        path: build/libs/*.jar
        compression-level: 0